import { chromium } from 'playwright';
const B = 'http://localhost:4140';
const errors = [];
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await browser.newPage();
page.on('pageerror', (e) => errors.push('PAGEERROR: ' + e.message));
await page.goto(B + '/');
await page.click('[data-auth="register"]');
await page.fill('input[name="name"]','M'); await page.fill('input[name="email"]','o@test.de'); await page.fill('input[name="password"]','geheim123');
await page.click('#auth-form button[type=submit]');
await page.waitForURL('**/app');
const opts = await page.locator('#manual-kind option').allInnerTexts();
console.log('Dropdown-Reihenfolge:');
opts.forEach((o,i)=>console.log(`  ${i}: ${o}`));
const hasCodes = opts.some(o=>/\(\d{4}\)/.test(o));
const dividerIdx = opts.findIndex(o=>/──/.test(o));
console.log('Enthält noch Codes:', hasCodes, '(erwartet false)');
console.log('Trennlinie an Position:', dividerIdx);
console.log('JS-Fehler:', errors.length ? errors : 'keine');
await browser.close();
process.exit(errors.length?1:0);
