import { chromium } from 'playwright';
const B = 'http://localhost:4270';
const errors = [];
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await browser.newPage();
page.on('pageerror', (e) => errors.push('PAGEERROR: ' + e.message));
await page.goto(B + '/');
await page.click('[data-auth="register"]');
await page.fill('input[name="name"]','M'); await page.fill('input[name="email"]','pf@test.de'); await page.fill('input[name="password"]','geheim123');
await page.click('#auth-form button[type=submit]');
await page.waitForURL('**/app');
const ovExists = await page.locator('#ov-pause').count();
await page.click('#start-btn'); await page.waitForTimeout(400);
await page.click('#pause-gehen-now'); await page.waitForTimeout(400);
const meta = (await page.textContent('#timer-meta')).trim();
const gehenDisabled = await page.locator('#pause-gehen-now').isDisabled();
await page.waitForTimeout(2100);
const pauseTickA = (await page.textContent('#ov-pause')).trim();
await page.click('#pause-kommen-now'); await page.waitForTimeout(500);
const badges = await page.locator('#entries-body .badge').allInnerTexts();
const pauseAfter = (await page.textContent('#ov-pause')).trim();
console.log('#ov-pause initial vorhanden:', ovExists);
console.log('Meta in Pause:', meta);
console.log('gehen disabled während Pause:', gehenDisabled);
console.log('Pause-Kachel tickt (~2s):', pauseTickA, '(sollte >0 sein)');
console.log('Badges nach Ende:', badges);
console.log('Pause-Kachel nach Ende:', pauseAfter);
console.log('JS-Fehler:', errors.length ? errors : 'keine');
await browser.close();
process.exit(errors.length?1:0);
